### ISSUE TITLE
Add Tracks Section

### ISSUE THREAD

**Issue by kirav5** [Repozo/dscjiit-hackathon#6]
## Add Tracks Section 
Take refence here - [Kuhackfest](https://www.kuhackfest.com/)
#### Expected Output
![image](https://user-images.githubusercontent.com/42544589/105036439-7c254e00-5a82-11eb-80e8-345caaef205e.png)

**Comment by akshatjain-akj** [comment]
#7 this pull request will add track section

**Comment by kirav5** [comment]
Cool for now
